### ISSUE TITLE
bug of "scroll.closestContentLayer" method?

### ISSUE THREAD

**Issue by hanfeisun** [koenbok/Framer#237]
Here is the code:

```
scroll = new ScrollComponent()

# Create content layers
layerA = new Layer({
    superLayer: scroll.content,
    x: 0, y: 0, name: "layerA"
})

layerB = new Layer({
    superLayer: scroll.content,
    x: 50, y: 50, name: "layerB"
})

print scroll.closestContentLayer(0.9, 0.9)
```

What is expected to be printed here is "layerB", however, when I run it in FramerStudio 1.13.1, the result is "layerA"..

**Comment by jchavarri** [comment]
I think this is the expected behavior. If I'm not wrong:

- Layer A frame is `{x:0, y: 0, width: 100, height:100}`
- Layer B frame is `{x:50, y: 50, width: 100, height:100}`
- Scroll frame is `{x:0, y: 0, width: 100, height:100}`

So if we suppose that pointA is the point of LayerA at position 0.9, 0.9:
`{x: 90, y:90}`

PointB is the point of LayerB at position 0.9, 0.9:
`{x: 140, y: 140}`

And pointScroll is the point of Scroll at position 0.9, 0.9:
`{x: 90, y:90}`

Then we see that actually the closest layer is *layerA*. You can check the difference if you change the width and height of layers A and B to 50 instead of 100. In that case, you'll see that layerB is the closest one.

Another discussion would be if that this `closestContentLayer` method is clear enough :)

**Comment by nvh** [comment]
I'm going to close this due to inactivity. Please feel free to open a new issue or keep commenting if you want to follow up on this.
