### ISSUE TITLE
Framer Studio violates expected coffeescript behavior

### ISSUE THREAD

**Issue by noAlvaro** [koenbok/Framer#283]
The code below works perfectly in coffeescript. But when using Framer Studio's `print` method it will throw `TypeError: undefined is not a object (evaluating 'v.constructor')`.

    Object::test = (props...) -> v.constructor for p, v of @
    alert/print { a: 1, b: 2, c: [1,2], d:{pt:true, pf:false}, e:'test', f:false }.test()

_Is it a bug?_

**Comment by nvh** [comment]
This is kind of a bug, but I don't think we're ever going to fix it.
Extending `Object` in JavaScript is a pretty dangerous thing to do, because pretty much _everything_ is an `Object`. There are serval places in the Framer Library where we iterate all the properties of an object expecting certain values. 

One of these iterations is causing this bug.

If you absolutely need to do this, be prepared that your function can be called at any time, in any context and scope/binding. And even if you account for that, it may change the behaviour of the Framer Library in unexpected ways.

I'm closing this now, if you have more to add here please feel free to do so.

**Comment by noAlvaro** [comment]
Alright thanks for the tip.
