### ISSUE TITLE
LayerStates::switch() behavior suggestion: Ignore switches to current state

### ISSUE THREAD

**Issue by IanBellomy** [koenbok/Framer#357]
Calling layer.states.switch(STATE_NAME) when the current state is STATE_NAME triggers an animation to that state. However, it _may_ be better to ignore switches to the same state. 

A common need when creating custom event detection is to check a condition and also a flag. 
e.g. 

```
if ~cursor in bounds~ AND not over { 
    over = true 
    animateOver()
}
```

If the state system ignored calls to the same state, the above could be

```
if ~cursor in bounds~ {
    states.switch("over")
}
```

Presently, switching to the same state causes visual animation stuttering as the same animation (with an ease-in) is started repeatedly; I can't think of a case where this (the standard) behavior would be desired.  

I can think of three reasons _not_ to make this change: 

- It allows (or encourages) code that hides the actual event triggering logic. 
- It's ambiguous what layer.states.switch(CURRENT_STATE) should return.

**Comment by eelco** [comment]
This is a very will written proposal, with pros and cons even! Thank you.

I ran into this myself while making some prototypes and I think it makes sense. I don’t think it encourages bad coding practices per se, and it sure would clean up a lot of (error prone) bookkeeping in some cases.

It’s hard to estimate the impact though, but some of that is because we don’t really have the tools (yet) to test changes like this. It also depends on what we do with the events though: should switching to the same state still trigger a willChange and didChange event? My hunch is that it’s best to turn switching to the same state to a no-op.

@koenbok Thoughts?

(BTW, I’m very curious about the third reason not to do this (or why you removed it) ;)

**Comment by IanBellomy** [comment]
Regarding the third item, I forgot! 

It may have been that it'd impact existing code (but I suspect the existing behavior is rarely, if ever, used intentionally), or a concern about adding an extra function call or conditional (I don't much of anything about contemporary Javascript compilers though). 

I agree with your thoughts on will/didChange. I'd think that CoffeeScripts has a preferred way of dealing with things like this though.

**Comment by nvh** [comment]
I think we should do this. As @eelco set, there's no way to test this, but we can make the new behaviour part of #378. Will implement it on https://github.com/koenbok/Framer/tree/feature/animation-refactor

**Comment by koenbok** [comment]
👌

**Comment by nvh** [comment]
Implemented. Current logic:

If the state name is the current we won't switch, _unless_ we the properties of the defined stated don't match with the current properties of the layer.

See the changes here: https://github.com/koenbok/Framer/compare/a88713b662778bc108128b12998a989f440512f0...85e145a790d8fdda36c0e71d93316d2bd1c554af
