### ISSUE TITLE
onload event

### ISSUE THREAD

**Issue by frederickk** [koenbok/Framer#435]
I'm working on a project and I would like to trigger and method once Framer (or the document) has been initially loaded (e.g. page is ready). I dug into [Events.coffee](https://github.com/koenbok/Framer/blob/ec784c9666614e3533d5b8adeedf86d4dc03cba6/framer/Events.coffee) but there's nothing in there for document/window handling.

I've tried the following:

```
// Doesn't fire
window.onload = function() {
    console.log('window.onload');
};

// Doesn't fire
document.onload = function() {
    console.log('document.onload');
};

// Doesn't fire
document.addEventListener('DOMContentLoaded', function() {
    console.log('DOMContentLoaded');
});

// Fires in Framer Studio, but not when deployed to browser
if (document.readyState != 'loading') {
    console.log('document.readyState', document.readyState);
}

// Fires in Framer Studio, but not when deployed to browser
(function() {
    console.log('self-calling');
})();
```

Any tips would be very much appreciated.

Thanks,
Ken

**Comment by eelco** [comment]
Framer Studio has a fast way of reloading the code, which the browser does not have. But in general, checking if the DOM in ready page is loaded is not a concern you need to care about in Framer, because your script will only execute once the page is ready. Just put the code you want to run immediately at the top of your script.
