### ISSUE TITLE
Clipping glitch with Flow component

### ISSUE THREAD

**Issue by briannhinton** [koenbok/Framer#454]
On initial load, and until a press occurs the flow component pieces are showing outside of the clip parent. 

See here: https://github.com/briannhinton/framer-bucket/blob/master/flow-app.js

Let me know if it's an error on my part as I'm still learning the Framer library.

**Comment by eelco** [comment]
You’re correct. This is not a bug per-se, as usually the layers are already set up in a way that they are clipped by the device screen. In this case, using the fullscreen device, you’ll have to do a bit of extra plumbing yourself. 

I think a good way to do it is setting the parent of each layer to the flow component in advance (which otherwise will happen when `showNext` is used), e.g. if you include `layerB.parent = flow` your example will work as expected.
