### ISSUE TITLE
Importing Sketch/PSD Layers Without Using Framer Studio

### ISSUE THREAD

**Issue by squibdib** [koenbok/Framer#506]
Is there a way to import Sketch or PSD files into a Framer prototype using just the open source codebase (i.e. without Studio)?  I know I can just import the layers as images one by one but I was wondering if it was possible to import them all simultaneously as layer groups.  

Thanks!

**Comment by nickonometry** [comment]
I've been trying to do this as well, I've been doing a lot of research and even tried several Photoshop scripts, no luck though. The problem is getting a proper JSON file with the PSD information in the correct format for framer. Framer studio is usually what outputs this JSON file. There's several 3rd party windows applications that may be able to handle this, but I was hoping for a 100% free approach.

**Comment by d4rekanguok** [comment]
@squibdib I think you could write a custom Sketch script that export layers into a selected Framer project

**Comment by rootscript** [comment]
Have you tried using `Framer Generator` that come with Framer.js?
You can import from Sketch & Photoshop.
![](https://cdn-images-1.medium.com/max/1600/1*RVYXWh445Ox9Aw4kIUkLow.png "Framer Generato Image")

**Comment by squibdib** [comment]
@rootscript The generator seems fine but actually that Sketch plugin seems to have done the trick :D
