### ISSUE TITLE
Unable to edit Github examples in Framer JS or Framer Studio!

### ISSUE THREAD

**Issue by FramerFun** [koenbok/Framer#536]
Could someone help on this issue please? Each time I open a new project imported from Github, Framer displays this message: "This version of Framer only works with the latest Framer library. Changes to the Framer library can lead to unexpected behavior in your project¨. When I click on "Try anyway", the project open but on the code is visible, not the design.

Thanks a lot for your help!

**Comment by eelco** [comment]
Each project contains it’s own copy of the Framer Library. However, not all versions of the Framer Library are compatible with the Framer app. 

That’s why, when opening “old” projects, you can see a message about upgrading. Usually you can click a button and a project will get updated (and might need some minor changes). 

When introducing Framer Design however, we also switched from coordinates representing pixels to points. We decided this change was too big to automatically upgrade projects, because it would definitely not work anymore. However, outdated projects are also not compatible with Design.

So, if you want to use example code in a new document. You can open the old project and a new document and then copy-paste the example code to the new document. You might need to go through and fix some things to make it work as expected. See the upgrade guide for more info: https://github.com/koenbok/Framer/wiki/DPR-Upgrade-Guide

**Comment by FramerFun** [comment]
Hi eelco,

Thanks for your reply.

I did exactly what is mentioned in the "DPR Upgrade Guide". I now can see the design tab but I did not see the Sketch files of the initial project. In my new project, I see only the code and no images in the design tab. I am using Framer Studio V99.

Could you please help me on that, so I can import all elements from the initial project to my new project.

Many thanks.
